# Generated by Django 4.2.27 on 2026-01-01 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRateReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_timestamp', models.BigIntegerField(help_text='Sensor timestamp in nanoseconds')),
                ('bpm', models.IntegerField(help_text='Heart rate in beats per minute')),
                ('rr_interval', models.IntegerField(help_text='RR interval in milliseconds')),
                ('energy', models.FloatField(blank=True, help_text='Energy expenditure in kilojoules (if available)', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the reading was stored in database')),
            ],
            options={
                'verbose_name': 'Heart Rate Reading',
                'verbose_name_plural': 'Heart Rate Readings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sensor_timestamp'], name='heartrate_h_sensor__f239a4_idx'), models.Index(fields=['created_at'], name='heartrate_h_created_aefbb6_idx'), models.Index(fields=['bpm'], name='heartrate_h_bpm_e227ed_idx')],
            },
        ),
    ]
